title: Mortimus
tagline: A blog around my cybersecurity journey
description: A blog around my cybersecurity journey
tags:
  - Cybersecurity
  - Pentesting
  - Red Team
  - Hacking
  - Offensive Cybersecurity

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/
author: Mortimus

show_downloads: false
google_analytics: true
theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap