title: Mortimus
tagline: A blog around my cybersecurity journey
description: A blog around my cybersecurity journey
tags:
  - Cybersecurity
  - Pentesting
  - Red Team
  - Hacking
  - Offensive Cybersecurity
show_downloads: false
google_analytics: true
theme: jekyll-theme-hacker
github:
  is_project_page: false